version: '3.5'
services:

  # This section is for starting elasticsearch
  elastic:
    # Calls the image:version of elasticsearch to use.
    ## Since no build variable exists, pulls from docker hub if image not present.
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VER}
    # What to name the running container
    container_name: elastic
    # Used to connect container to the host network
    network_mode: host
    # If the container crashes, always restart it
    restart: always
    # ulimit is the number of open file descriptors per process.
    ulimits:
      # memlock option is used to set the maximum amount of locked-in-memory address space as given in kilobytes.
      memlock:
        # Soft limit is the limit enforced by kernel.
        soft: -1
        # Hard limit is the ceiling for the resource value for unprivileged processes
        ## which can raise its soft limit only to this value.
        hard: -1
    environment:
      # Sets elastic to run as only a single node. Only change this if you "think" you know what you are doing.
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html#single-node-discovery
      - discovery.type=single-node
    # Shares between the host system and the container for "ease of editing"/"persistence of data"
    volumes:
      # Mounts host:container volume to allow access/persistence to files running in the container.
      - ./elastic/moloch-data:/usr/share/elasticsearch/data:Z # Node data for elasticsearch persistence.

  # This section is for starting arkime
  arkime:
    # Arkime image to use.
    image: arkime:latest
    # If the image doesn't exist build from this location. "." is the local directory
    build: ./arkime
    # What to name the running container
    container_name: arkime
    # Used to connect container to the host for collecting off the wire
    network_mode: host
    # ulimit is the number of open file descriptors per process.
    ulimits:
      # memlock option is used to set the maximum amount of locked-in-memory address space as given in kilobytes.
      memlock:
        # Soft limit is the limit enforced by kernel.
        soft: -1
        # Hard limit is the ceiling for the resource value for unprivilged processess
        ## which can raise its soft limit only to this value.
        hard: -1
    # Waits to start arkime until elasticsearch is running
    depends_on:
      - elastic
    # Shares between the host system and the container for "ease of editing"/"persistence of data"
    volumes:
      # Mounts host:container volume to allow access/persistence to files running in the container
      - ./arkime/logs:/data/moloch/logs/:Z # log files related to arkime
      - ./arkime/pcap:/data/pcap/:ro # pcap folder for ingesting new pcap
      - ./arkime/raw:/data/moloch/raw/:rw # pcap folder for processed pcap - stored as sessions2 data
      - ./arkime/config/config.ini:/data/moloch/etc/config.ini:rw # Config used for arkime settings
      - ./suricata/logs:/data/moloch/etc/suricata:z # Used to share alerts from suricata with arkime.
      - ./arkime/tags:/data/moloch/tags:Z # Used to store WISE tag files.
      - ./arkime/wise/wiseService.ini:/data/moloch/etc/wiseService.ini # Used to change the wise config file.
      - ./arkime/entrypoint/startarkime.sh:/data/startarkime.sh
      ## 1 = leave alone, init if anything else.
    # Add container capabilities - These may not be needed, but if use cases expand they may be.
    ## They are used on our kit's config and have been carried over.
    cap_add:
      - IPC_LOCK # Allows to lock shared memory segments and mlock/mlockall calls.
      - NET_RAW # Allow use of RAW and PACKET sockets.
      - NET_ADMIN # Allows interacting with network interface. ie - promiscuous mode.
      - SYS_NICE # Allows the container to raise process nice values, set real-time scheduling policies, set CPU affinity, and other operations.
    environment:
      - INIT=${INIT} # Initialize Arkime db as start? Needs to be done on first startup regardless.
      - CAPTURE=${CAPTURE} # Start Arkime-capture to pull off the wire and store as pcap.
      - INTERFACE=${INTERFACE}


  # This section is for starting kibana
  kibana:
    # Calls the image:version of kibana to use. Make sure the version matches elasticsearch.
    ## Since no build variable exists, pulls from docker hub if image not present.
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VER}
    # What to name the running container
    container_name: kibana
    # Used to connect container to the host network
    network_mode: host
    # Shares between the host system and the container for "ease of editing"/"persistence of data"
    volumes:
      # Mounts host:container volume to allow access/persistence to files running in the container
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:Z # Kibana config file. Mostly for adv users

  # This section is for starting suricata
  suricata:
    # Calls the image:version of suricata to use.
    image: suricata:6.0.0
    # If the image doesn't exist build from this location. "." is the local directory
    build: ./suricata
    # What to name the running container
    container_name: suricata
    # Used to connect container to the host for collecting off the wire
    network_mode: host
    # Add container capabilities - These may not be needed, but if use cases expand they may be.
    cap_add:
      - NET_ADMIN # Allows interacting with network interface. ie - promiscuous mode.
      - SYS_NICE # Allows the container to raise process nice values, set real-time scheduling policies, set CPU affinity, and other operations.
      # Shares between the host system and the container for "ease of editing"/"persistence of data"
    volumes:
      - ./suricata/rules:/etc/suricata/rules:z # Rules files.
      - ./suricata/etc/suricata.yaml/suricata.yaml:/etc/suricata/suricata.yaml:Z # Suricata.yaml to edit config
      - ./suricata/logs:/var/log/suricata:z # suricata logs for alerts and debug
    environment:
      - VERSION=${SURICATA_VERSION}
    command: suricata --af-packet=${INTERFACE}

  zeek:
    # Calls the image:version of zeek to use.
    image: zeek:latest
    # If the image doesn't exist build from this location. "." is the local directory
    build: ./zeek
    # What to name the running container
    container_name: zeek
    # Used to connect container to the host for collecting off the wire
    network_mode: host
    # ulimit is the number of open file descriptors per process.
    ulimits:
      # memlock option is used to set the maximum amount of locked-in-memory address space as given in kilobytes.
      memlock:
        # Soft limit is the limit enforced by kernel.
        soft: -1
        # Hard limit is the ceiling for the resource value for unprivileged processes
        ## which can raise its soft limit only to this value.
        hard: -1
      # Add container capabilities - These may not be needed, but if use cases expand they may be.
    cap_add:
      - NET_RAW # Allow use of RAW and PACKET sockets.
      # Shares between the host system and the container for "ease of editing"/"persistence of data"
    volumes:
      - ./zeek/logs:/zeek # zeek logs
      - ./zeek/pcap:/pcap # pcap location for zeek access
      - ./zeek/config:/opt/zeek/etc/ # zeek config file locations. Likely not needed.
    command: /opt/zeek/bin/zeek -i ${INTERFACE} LogAscii::use_json=T
  
  # This section is for starting zeek
  filebeat:
    # Calls the image:version of zeek to use.
    image: docker.elastic.co/beats/filebeat:${ELASTIC_VER}
    # What to name the running container
    container_name: filebeat
    # Waits to start arkime until elasticsearch is running
    depends_on:
      - elastic
      - zeek
    # Used to connect container to the host network
    network_mode: host
    # Shares between the host system and the container for "ease of editing"/"persistence of data"
    volumes:
      # Mounts host:container volume to allow access/persistence to files running in the container
      - ./zeek/logs:/data/zeek # zeek log output directory for parsing by filebeat.
      - ./filebeat/config/zeek.yml:/usr/share/filebeat/modules.d/zeek.yml:ro # config file setting zeek log location.
      - ./filebeat/config/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro # filebeat config file. Mostly for adv users.
    command: filebeat -e -strict.perms=false