# Module: zeek
# Docs: https://www.elastic.co/guide/en/beats/filebeat/7.10/filebeat-module-zeek.html

- module: zeek
  capture_loss:
    enabled: true
    var.paths: ["/data/zeek/capture_loss.log"]
  connection:
    enabled: true
    var.paths: ["/data/zeek/conn.log"]
  dce_rpc:
    enabled: true
    var.paths: ["/data/zeek/dce_rpc.log"]
  dhcp:
    enabled: true
    var.paths: ["/data/zeek/dhcp.log"]
  dnp3:
    enabled: true
    var.paths: ["/data/zeek/dnp3.log"]
  dns:
    enabled: true
    var.paths: ["/data/zeek/dns.log"]
  dpd:
    enabled: true
    var.paths: ["/data/zeek/dpd.log"]
  files:
    enabled: true
    var.paths: ["/data/zeek/files.log"]
  ftp:
    enabled: true
    var.paths: ["/data/zeek/ftp.log"]
  http:
    enabled: true
    var.paths: ["/data/zeek/http.log"]
  intel:
    enabled: true    
    var.paths: ["/data/zeek/intel.log"]
  irc:
    enabled: true
    var.paths: ["/data/zeek/irc.log"]
  kerberos:
    enabled: true
    var.paths: ["/data/zeek/kerberos.log"]
  modbus:
    enabled: true
    var.paths: ["/data/zeek/modbus.log"]
  mysql:
    enabled: true
    var.paths: ["/data/zeek/mysql.log"]
  notice:
    enabled: true
    var.paths: ["/data/zeek/notice.log"]
  ntlm:
    enabled: true
    var.paths: ["/data/zeek/ntlm.log"]
  ocsp:
    enabled: true
    var.paths: ["/data/zeek/ocsp.log"]
  pe:
    enabled: true
    var.paths: ["/data/zeek/pe.log"]
  radius:
    enabled: true
    var.paths: ["/data/zeek/radius.log"]
  rdp:
    enabled: true
    var.paths: ["/data/zeek/rdp.log"]
  rfb:
    enabled: true
    var.paths: ["/data/zeek/rfb.log"]
  sip:
    enabled: true
    var.paths: ["/data/zeek/sip.log"]
  smb_cmd:
    enabled: true
    var.paths: ["/data/zeek/smb_cmd.log"]
  smb_files:
    enabled: true
    var.paths: ["/data/zeek/smb_files.log"]
  smb_mapping:
    enabled: true
    var.paths: ["/data/zeek/smb_mappings.log"]
  smtp:
    enabled: true
    var.paths: ["/data/zeek/smtp.log"]
  snmp:
    enabled: true
    var.paths: ["/data/zeek/snmp.log"]
  socks:
    enabled: true
    var.paths: ["/data/zeek/socks.log"]
  ssh:
    enabled: true
    var.paths: ["/data/zeek/ssh.log"]
  ssl:
    enabled: true
    var.paths: ["/data/zeek/ssl.log"]
  stats:
    enabled: true
    var.paths: ["/data/zeek/stats.log"]
  syslog:
    enabled: true
    var.paths: ["/data/zeek/syslog.log"]
  traceroute:
    enabled: true
    var.paths: ["/data/zeek/traceroute.log"]
  tunnel:
    enabled: true
    var.paths: ["/data/zeek/tunnel.log"]
  weird:
    enabled: true
    var.paths: ["/data/zeek/weird.log"]
  x509:
    enabled: true
    var.paths: ["/data/zeek/x509.log"]

    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    #var.paths: